name: ESXi-Deployment
env:
  VSPHERE_HOST: "${{ secrets.ESXI_HOST }}"
  VSPHERE_USERNAME: "${{ secrets.ESXI_USER }}"
  VSPHERE_PASSWORD: "${{ secrets.ESXI_PASSWORD }}"
  OVA_PATH: /home/runner/work/GW-Releases/GW-Releases/k8-rebuild-centos-23da99531185dc4e8b0084fd5c476a05a2547ea7-31.ova
  # OVA_PATH: "${{ github.event.inputs.OVA_PATH }}"
  VM_NAME: "${{ github.event.inputs.VM_NAME }}"

on:
  workflow_dispatch:
    inputs:
      OVA_PATH:
        description: Direct download link for the OVA
        required: true
      VM_NAME:
        description: VM name on ESXi after deployment
        default: workflow-deploy-vm
        required: true
  push:
    branches: [ ova_deployment ]    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GW-Releases
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install k8-py-vmware
      run: |
        pwd
        ls
        cd ..
        pwd
        echo "Python version: $(python3 --version)"
        sudo apt-get install python3-setuptools
        sudo pip3 install wheel
        git clone https://github.com/k8-proxy/k8-py-vmware.git
        cd k8-py-vmware
        sudo pip3 install -r requirements.txt
        sudo pip3 install -e .
        echo "pip libraries installed"
        pip3 list

    - name: Install dependencies
      run: |
        pwd
        cd ..
        pwd
        sudo cp -r k8-py-vmware/k8_vmware GW-Releases/vmware-scripts/scripts
        cd GW-Releases/vmware-scripts/scripts/automated-deployment
        pip3 install -r requirements.txt
        echo "completed installing dependancies!!"
        
    - name: Run ova deployment
      run: |
        pwd
        sudo apt install wget -y
        sudo wget https://glasswall-sow-ova.s3-eu-west-1.amazonaws.com/vms/k8-rebuild-centos/k8-rebuild-centos-23da99531185dc4e8b0084fd5c476a05a2547ea7-31.ova
        cd vmware-scripts/scripts
        python3 -m automated-deployment.src.VM_deploy_ova

